AllCops:
  NewCops: disable
  TargetRubyVersion: 3.3
  Include:
    - '**/*.rb'
    - rakelib/*.rake
    - 'Gemfile'
    - 'Rakefile'
    - 'reveal-ck.gemspec'
    - 'files/reveal-ck/Guardfile'
  Exclude:
    - tmp/**/*
    - files/reveal.js/**/*

Naming/FileName:
  Exclude:
    - Gemfile
    - reveal-ck.gemspec
    - lib/reveal-ck.rb
    - files/reveal-ck/Guardfile

Style/RescueStandardError:
  Exclude:
    - lib/reveal-ck/commands/serve.rb

Style/FrozenStringLiteralComment:
  Exclude:
    - '**/*'

Metrics/BlockLength:
  Exclude:
    - bin/reveal-ck
    - reveal-ck.gemspec
    - spec/**/*.rb

Metrics/CyclomaticComplexity:
  Max: 6

Lint/MissingSuper:
  Exclude:
    - lib/reveal-ck/builders/slides_builder.rb
    - lib/reveal-ck/rake_task.rb

Lint/ConstantDefinitionInBlock:
  Exclude:
    - spec/lib/reveal-ck/misc/remove_extension_spec.rb

Metrics/MethodLength:
  Exclude:
    - bin/reveal-ck
    - lib/reveal-ck/config.rb
    - lib/reveal-ck/builders/create_index_html.rb

Naming/MethodParameterName:
  MinNameLength: 1
