Metrics/CyclomaticComplexity:
  Max: 5

AllCops:
  Include:
    - '**/*.rb'
    - rakelib/*.rake
    - 'Gemfile'
    - 'Rakefile'
    - 'reveal-ck.gemspec'
    - 'files/reveal-ck/Guardfile'
  Exclude:
    - tmp/**/*
    - files/reveal.js/**/*

Gemspec/RequiredRubyVersion:
  Exclude:
    - 'reveal-ck.gemspec'

Naming/FileName:
  Exclude:
    - Gemfile
    - reveal-ck.gemspec
    - lib/reveal-ck.rb
    - files/reveal-ck/Guardfile

Style/RescueStandardError:
  Exclude:
    - lib/reveal-ck/commands/serve.rb

Style/FrozenStringLiteralComment:
  Exclude:
    - '**/*'

Metrics/BlockLength:
  Exclude:
    - bin/reveal-ck
    - reveal-ck.gemspec
    - spec/**/*.rb

Metrics/MethodLength:
  Exclude:
    - bin/reveal-ck
    - lib/reveal-ck/config.rb
    - lib/reveal-ck/builders/create_index_html.rb

Naming/MethodParameterName:
  MinNameLength: 1
