# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "reveal-ck"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jed Northridge"]
  s.date = "2013-01-30"
  s.description = "A reveal.js construction kit"
  s.email = "northridge@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".gitmodules",
    ".rspec",
    ".rvmrc",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/reveal-ck.rb",
    "lib/reveal-ck/file_slicer.rb",
    "lib/reveal-ck/file_splicer.rb",
    "lib/reveal-ck/haml_processor.rb",
    "reveal-ck.gemspec",
    "slides.haml",
    "slides.html",
    "spec/data/haml/basic.haml",
    "spec/data/html/converted_basic_haml.html",
    "spec/data/html/reveal-js-index.html",
    "spec/data/slicer/after_remove",
    "spec/data/slicer/before_remove",
    "spec/data/splicer/abcd",
    "spec/data/splicer/after_insert",
    "spec/data/splicer/before_insert",
    "spec/lib/reveal-ck/file_slicer_spec.rb",
    "spec/lib/reveal-ck/file_splicer_spec.rb",
    "spec/lib/reveal-ck/haml_processor_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "https://github.com/jedcn/reveal-ck"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "A toolkit that takes a minimal description of slides and builds a reveal.js presentation"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
    else
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
    end
  else
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
  end
end

