require_relative 'render/contents_of'
require_relative 'render/css_files'
require_relative 'render/js_files'
require_relative 'render/plugin_files'
require_relative 'render/index_html_maker'
require_relative 'render/scope'
